### ISSUE TITLE
Cannot successfully install with Obsidian 1.4.13

### ISSUE THREAD

**Issue by viking2917** [coddingtonbear/obsidian-local-rest-api#76]
After upgrading to Obsidian 1.4.13, I cannot get this plugin to install any more (it was working in a previous version of Obsidian). 

When I install the plugin, Obsidian says it successfully installed it, however it does not show in the list of installed plugins and I cannot connect via the local rest API through either https://coddingtonbear.github.io/obsidian-local-rest-api/ or the Obsidian Web chrome plugin. 

Other community plugins install correctly. 

The Obsidian developer console shows these errors, prior to the attempted installation, not sure if those are 'normal' errors or whether something is messed up in my install:

```
app.js:1 SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at e.<anonymous> (app.js:1:2032250)
    at app.js:1:237030
    at Object.next (app.js:1:237135)
    at a (app.js:1:235853)
(anonymous) @ app.js:1
app.js:1 SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at t.<anonymous> (app.js:1:706510)
    at app.js:1:237030
    at Object.next (app.js:1:237135)
    at a (app.js:1:235853)
```

Has anyone been successful with 1.4.13? Or perhaps something is messed up in my installation?

**Comment by viking2917** [comment]
I updated to Obsidian 1.4.14 and the problem went away. Closing this. Thanks for this plugin!
